apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: quarkus-workshop
  namespace: quarkus-workshop
spec:
  targetNamespaces:
  - quarkus-workshop
  
---

apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: postgresql-operator-dev4devs-coml
  namespace: quarkus-workshop
spec:
  channel: "alpha"
  name: postgresql-operator-dev4devs-com
  source: community-operators
  sourceNamespace: openshift-marketplace
  
---

apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: strimzi-kafka-operator
  namespace: quarkus-workshop
spec:
  channel: "strimzi-0.22.x"
  name: strimzi-kafka-operator
  source: community-operators
  sourceNamespace: openshift-marketplace

    


  
  